name: creedo
services:
    web:
        image: clover/openresty

        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./nginx/conf.d/:/usr/local/openresty/nginx/conf/conf.d/
            - ../app:/var/www/html
        depends_on:
            - php
        links:
            - php:php

    php:
        build:
            context: .
        volumes:
            - ../app:/var/www/html
        depends_on:
            - mongo
        links:
            - mongo:db
    mongo:
        image: mongo:8
        container_name: my-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-ui
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        links:
            - mongo:db

volumes:
  mongo_data: